"""crear tablas iniciales

Revision ID: f83b02aca16a
Revises: 
Create Date: 2026-06-11 16:14:28.582906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f83b02aca16a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plan_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuenta_nube',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_organizacion', sa.UUID(), nullable=False),
    sa.Column('proveedor', sa.Enum('azure', 'aws', 'gcp', name='proveedor_enum'), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('credenciales', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'error', 'desconectada', name='estado_cuenta_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_organizacion', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estado_usuario_enum'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ambito_nodo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_nube', sa.UUID(), nullable=False),
    sa.Column('padre_id', sa.UUID(), nullable=True),
    sa.Column('tipo_nodo', sa.String(length=30), nullable=False),
    sa.Column('proveedor_ref_id', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_nube'], ['cuenta_nube.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['ambito_nodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_ambito_nodo', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('propietario', 'lector', 'facturacion', name='rol_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_ambito_nodo'], ['ambito_nodo.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_ambito_nodo')
    )
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ambito_nodo', sa.UUID(), nullable=False),
    sa.Column('recurso_ref_id', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=45), nullable=False),
    sa.Column('ubicacion', sa.String(length=45), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'detenido', 'eliminado', name='tipo_enum'), nullable=False),
    sa.Column('propiedades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_ambito_nodo'], ['ambito_nodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.Enum('info', 'warning', 'high', 'critical', name='severidad_enum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('solucion', sa.Text(), nullable=True),
    sa.Column('ahorro_estimado', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'resuelta', 'ignorada', name='estado_anomalia_enum'), nullable=True),
    sa.Column('detectada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['recurso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_coste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('coste', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('moneda', sa.Enum('EUR', 'USD', name='moneda_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['recurso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_coste')
    op.drop_table('anomalia')
    op.drop_table('recurso')
    op.drop_table('permisos')
    op.drop_table('ambito_nodo')
    op.drop_table('usuario')
    op.drop_table('cuenta_nube')
    op.drop_table('organizacion')
    # ### end Alembic commands ###
